version: '2'

services:
    apache;
        image: suse/apache2:latest
        restart: unless-stopped
        links: 
            - rocketchat
        volumes:
            - /home/rashford/git/darthzen/build/apache/docker/vhosts:/etc/apache2/vhosts.d
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - /etc/ssl:/etc/ssl
        tmpfs:
            - /tmp
            - /run
    rocketchat:
        image: suse/rocket.chat:latest
        restart: unless-stopped
        links: 
            - mongo
        volumes:
            - /home/rashford/git/darthzen/build/rocket.chat/docker/uploads:/srv/www/rocket.chat/uploads
        environment:
            - PORT=3000
            - ROOT_URL=http://localhost:3000
            - MONGO_URL=mongodb://mongo:27017/rocketchat
            - Accounts_AvatarStorePath=/srv/www/rocket.chat/uploads
        depends_on:
            - mongo
        ports:
            - 443:443

    mongo:
        image: suse/mongodb:latest
        restart: unless-stopped
        volumes:
         - /home/rashford/git/darthzen/build/mongodb/docker/data:/var/lib/mongodb

    mongo-init-replica:
        image: suse/mongodb:latest
        command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rocketchat'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
        depends_on:
            - mongo

